services:
  - type: web
    name: orcoma-academy-api
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput
    startCommand: gunicorn orcoma_academy.wsgi:application
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: ALLOWED_HOSTS
        value: "orcoma-academy-backend.onrender.com,orcoma-academy.vercel.app,academy.orcoma.com.br,localhost,127.0.0.1"
      - key: PYTHON_VERSION
        value: "3.12"

  - type: cron
    name: orcoma-keep-alive
    runtime: python
    buildCommand: pip install requests
    schedule: "*/10 * * * *"
    startCommand: python keep_alive.py
    envVars:
      - key: APP_URL
        value: "https://orcoma-academy-api.onrender.com/api/ping/"


