services:
  - type: web
    name: orcoma-academy-api
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput
    startCommand: gunicorn orcoma_academy.wsgi:application --workers 2 --threads 2 --timeout 120 --worker-class sync
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: ALLOWED_HOSTS
        value: "orcoma-academy-backend.onrender.com,visao-tributaria.vercel.app,orc-academy.vercel.app,orcoma-academy.vercel.app,academy.orcoma.com.br,dashboard.orcomacontabilidade.com.br,dashboard-visao.onrender.com,localhost,127.0.0.1"
      - key: RECAPTCHA_SECRET_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.12.0"

  - type: cron
    name: orcoma-keep-alive
    runtime: python
    buildCommand: pip install requests
    schedule: "*/5 * * * *"
    startCommand: python keep_alive.py
    envVars:
      - key: APP_URL
        value: "https://orcoma-academy-backend.onrender.com/api/ping/"
      - key: PYTHON_VERSION
        value: "3.12"


