# Generated by Django 6.0.6 on 2026-07-07 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='capacidade',
            field=models.PositiveIntegerField(default=0, help_text='0 = sem limite'),
        ),
        migrations.CreateModel(
            name='CursoVisualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualizado_em', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='core.curso')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visualizacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visualização de Curso',
                'verbose_name_plural': 'Visualizações de Cursos',
                'ordering': ['-visualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('progresso', models.PositiveIntegerField(default=0, help_text='Percentual 0-100')),
                ('concluido', models.BooleanField(default=False)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='core.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'ordering': ['-data_inscricao'],
                'unique_together': {('usuario', 'curso')},
            },
        ),
    ]
