# Generated by Django 6.0.6 on 2026-07-08 12:50

from django.db import migrations


def popular_ambientes(apps, schema_editor):
    Ambiente = apps.get_model('core', 'Ambiente')
    ambientes = [
        'Academy Contábil',
        'Academy Gestão Empresarial',
        'Academy Team',
        'Academy Orcomakers',
    ]
    for nome in ambientes:
        Ambiente.objects.get_or_create(nome=nome)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ambiente_plano_ambientes'),
    ]

    operations = [
        migrations.RunPython(popular_ambientes),
    ]
