# Generated by Django 6.0.6 on 2026-07-08 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_popular_ambientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trilha',
            name='ambiente',
        ),
        migrations.AddField(
            model_name='trilha',
            name='ambiente_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ambiente', verbose_name='Ambiente'),
        ),
    ]
