# Generated by Django 6.0.6 on 2026-07-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_trilha_ambiente_trilha_ambiente_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trilha',
            old_name='ambiente_fk',
            new_name='ambiente',
        ),
    ]
