# Generated by Django 6.0.6 on 2026-07-08 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_ambiente_fk_trilha_ambiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trilha',
            name='ambiente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.ambiente', verbose_name='Ambiente'),
            preserve_default=False,
        ),
    ]
