# Generated by Django 6.0.6 on 2026-07-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/thumbnails/', verbose_name='Thumbnail/Capa'),
        ),
        migrations.AddField(
            model_name='curso',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='cursos/videos/', verbose_name='Vídeo'),
        ),
    ]
