# Generated by Django 6.0.6 on 2026-07-10 17:43

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0011_curso_thumbnail_curso_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissao',
            fields=[
            ],
            options={
                'verbose_name': 'Permissão',
                'verbose_name_plural': 'Permissões',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='ambiente',
            options={'ordering': ['nome'], 'permissions': [('gerenciar_ambientes', 'Pode gerenciar ambientes')], 'verbose_name': 'Ambiente', 'verbose_name_plural': 'Ambientes'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['-created_at'], 'permissions': [('cadastrar_videos', 'Pode cadastrar vídeos'), ('editar_videos', 'Pode editar vídeos'), ('excluir_videos', 'Pode excluir vídeos'), ('publicar_cursos', 'Pode publicar cursos')], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['data'], 'permissions': [('gerenciar_eventos', 'Pode gerenciar eventos')], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='logatividade',
            options={'ordering': ['-created_at'], 'permissions': [('ver_logs_atividade', 'Pode ver logs de atividade')], 'verbose_name': 'Log de Atividade', 'verbose_name_plural': 'Logs de Atividades'},
        ),
        migrations.AlterModelOptions(
            name='novidade',
            options={'ordering': ['-created_at'], 'permissions': [('gerenciar_novidades', 'Pode gerenciar novidades')], 'verbose_name': 'Novidade', 'verbose_name_plural': 'Novidades'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'permissions': [('gerenciar_clientes', 'Pode gerenciar clientes'), ('remover_clientes', 'Pode remover clientes'), ('gerenciar_permissoes', 'Pode gerenciar permissões')], 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
        migrations.AlterModelOptions(
            name='plano',
            options={'ordering': ['nome'], 'permissions': [('gerenciar_planos', 'Pode gerenciar planos')], 'verbose_name': 'Plano', 'verbose_name_plural': 'Planos'},
        ),
        migrations.AlterModelOptions(
            name='trilha',
            options={'permissions': [('gerenciar_trilhas', 'Pode gerenciar trilhas')], 'verbose_name': 'Trilha', 'verbose_name_plural': 'Trilhas'},
        ),
    ]
