# Generated by Django 6.0.6 on 2026-07-10 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_permissao_alter_ambiente_options_alter_curso_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormacaoAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=255)),
                ('nivel', models.CharField(choices=[('tecnico', 'Técnico'), ('tecnologo', 'Tecnólogo'), ('bacharel', 'Bacharel'), ('posgraduado', 'Pós-graduado'), ('mestre', 'Mestre'), ('doutor', 'Doutor')], max_length=20)),
                ('area', models.CharField(max_length=255)),
                ('inicio_mes', models.CharField(max_length=20)),
                ('inicio_ano', models.CharField(max_length=4)),
                ('termino_mes', models.CharField(blank=True, max_length=20)),
                ('termino_ano', models.CharField(blank=True, max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formação Acadêmica',
                'verbose_name_plural': 'Formações Acadêmicas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['nome'],
            },
        ),
    ]
