# Generated by Django 6.0.6 on 2026-07-10 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_formacaoacademica_habilidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_contratacao', models.DateField()),
                ('data_expiracao', models.DateField()),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('expirada', 'Expirada'), ('cancelada', 'Cancelada')], default='ativa', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='core.plano')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assinatura de Plano',
                'verbose_name_plural': 'Assinaturas de Planos',
                'ordering': ['-data_contratacao'],
            },
        ),
    ]
