# Generated by Django 6.0.6 on 2026-07-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_assinaturaplano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinaturaplano',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativo'), ('inativo', 'Inativo'), ('expirada', 'Expirado'), ('cancelada', 'Cancelado')], default='ativa', max_length=20),
        ),
    ]
