# Generated by Django 6.0.6 on 2026-07-14 14:04

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_assinaturaplano_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcessoRoleAcademia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30, verbose_name='Perfil')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Acesso perfil × academy',
                'verbose_name_plural': 'Acessos perfil × academy',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='cursos/videos/', validators=[core.validators.validate_video_file], verbose_name='Arquivo de vídeo')),
                ('url_externa', models.URLField(blank=True, help_text='YouTube, Vimeo ou outro link. Use quando não houver upload.', verbose_name='URL externa')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vídeo',
                'verbose_name_plural': 'Vídeos',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='ambiente',
            options={'ordering': ['nome'], 'permissions': [('gerenciar_ambientes', 'Pode gerenciar academies')], 'verbose_name': 'Academy', 'verbose_name_plural': 'Academies'},
        ),
        migrations.AddField(
            model_name='ambiente',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academias', to='core.plano', verbose_name='Plano'),
        ),
        migrations.AddField(
            model_name='curso',
            name='academias_extras',
            field=models.ManyToManyField(blank=True, help_text='Academies adicionais com acesso pontual a este curso.', related_name='cursos_extras', to='core.ambiente', verbose_name='Academies extras'),
        ),
        migrations.AddField(
            model_name='curso',
            name='ambiente',
            field=models.ForeignKey(blank=True, help_text='Define em qual academy o curso aparece no site.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='core.ambiente', verbose_name='Academy'),
        ),
        migrations.AddField(
            model_name='curso',
            name='is_gratuito',
            field=models.BooleanField(default=False, help_text='Visível e acessível por todos os perfis, incluindo visitantes.', verbose_name='Gratuito'),
        ),
        migrations.AddField(
            model_name='curso',
            name='roles_extras',
            field=models.JSONField(blank=True, default=list, help_text='Perfis adicionais com acesso a este curso (ex.: ["empresario"]).', verbose_name='Perfis extras'),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Academy'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='video',
            field=models.FileField(blank=True, help_text='Campo legado. Prefira cadastrar aulas no inline "Vídeos".', null=True, upload_to='cursos/videos/', validators=[core.validators.validate_video_file], verbose_name='Vídeo (legado)'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('cliente_orcoma', 'Cliente Orcoma'), ('empresario', 'Empresário Não Cliente'), ('cliente_equipe', 'Cliente Equipe'), ('colaborador_orcoma', 'Colaborador Orcoma'), ('gestor_orcoma', 'Gestor Orcoma (interno)'), ('visitor', 'Visitante')], db_index=True, default='cliente_orcoma', max_length=30),
        ),
        migrations.AlterField(
            model_name='trilha',
            name='ambiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ambiente', verbose_name='Academy'),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['ambiente'], name='core_curso_ambient_702f93_idx'),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['is_gratuito'], name='core_curso_is_grat_5ab594_idx'),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['status'], name='core_curso_status_983625_idx'),
        ),
        migrations.AddField(
            model_name='acessoroleacademia',
            name='academia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos_role', to='core.ambiente', verbose_name='Academy'),
        ),
        migrations.AddField(
            model_name='video',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.curso'),
        ),
        migrations.AddIndex(
            model_name='acessoroleacademia',
            index=models.Index(fields=['role'], name='core_acesso_role_88b36c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='acessoroleacademia',
            unique_together={('role', 'academia')},
        ),
    ]
