# Generated by Django 6.0.6 on 2026-07-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_acessoroleacademia_video_alter_ambiente_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('cliente_premium', 'Cliente Premium'), ('cliente_orcoma', 'Cliente Orcoma'), ('empresario', 'Empresário Não Cliente'), ('cliente_equipe', 'Cliente Equipe'), ('colaborador_orcoma', 'Colaborador Orcoma'), ('gestor_orcoma', 'Gestor Orcoma (interno)'), ('visitor', 'Visitante')], db_index=True, default='cliente_orcoma', max_length=30),
        ),
    ]
