# Generated by Django 6.0.6 on 2026-07-14 20:54

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Curso = apps.get_model('core', 'Curso')
    for curso in Curso.objects.all():
        if not curso.slug:
            base_slug = slugify(curso.titulo)
            slug = base_slug
            counter = 1
            while Curso.objects.filter(slug=slug).exclude(pk=curso.pk).exists():
                slug = f'{base_slug}-{counter}'
                counter += 1
            curso.slug = slug
            curso.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_perfil_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identificador único no URL (ex: reforma-tributaria)', max_length=255),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='curso',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identificador único no URL (ex: reforma-tributaria)', max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='core.curso')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='cursos/materiais/', verbose_name='Arquivo')),
                ('url_externa', models.URLField(blank=True, help_text='Use quando o arquivo estiver hospedado em outro lugar.', verbose_name='URL externa')),
                ('modalidade', models.CharField(choices=[('pdf', 'PDF'), ('xls', 'Excel'), ('xlsx', 'Excel (XLSX)'), ('zip', 'ZIP'), ('link', 'Link Externo')], default='pdf', max_length=10)),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='core.modulo')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
