# Generated by Django 6.0.6 on 2026-07-16 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_modulo_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='ultimo_segundo_assistido',
            field=models.PositiveIntegerField(default=0, help_text='Último segundo do vídeo assistido'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='video_corrente',
            field=models.ForeignKey(blank=True, help_text='Último vídeo acessado pelo aluno neste curso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas_ultimo_video', to='core.video'),
        ),
    ]
