# Generated by Django 6.0.6 on 2026-07-16 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_video_position_to_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único de validação do certificado', max_length=30, unique=True)),
                ('emitido_em', models.DateTimeField(auto_now_add=True)),
                ('matricula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificado', to='core.matricula')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-emitido_em'],
            },
        ),
    ]
