# Generated by Django 6.0.6 on 2026-07-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_certificado_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='is_recomendado',
            field=models.BooleanField(default=False, help_text='Aparece na seção "Recomendado para você" nas academies.', verbose_name='Recomendado'),
        ),
    ]
