# Generated by Django 6.0.6 on 2026-07-17 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_curso_is_recomendado'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='modulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='core.modulo', verbose_name='Módulo'),
        ),
    ]
