# Generated by Django 6.0.6 on 2026-07-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_video_add_modulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/', verbose_name='Imagem'),
        ),
    ]
