# Generated by Django 6.0.6 on 2026-07-20 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_evento_imagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('meta_horas', models.PositiveIntegerField(default=5, help_text='Meta de horas semanais')),
                ('horas_concluidas', models.FloatField(default=0)),
                ('semana_inicio', models.DateField(help_text='Início da semana')),
                ('semana_fim', models.DateField(help_text='Fim da semana')),
                ('concluida', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_semanais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta Semanal',
                'verbose_name_plural': 'Metas Semanais',
                'ordering': ['-semana_inicio'],
            },
        ),
    ]
