# Generated by Django 6.0.6 on 2026-07-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_meta_semanal'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, verbose_name='CNPJ da Empresa'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone Corporativo'),
        ),
    ]
