# Generated by Django 6.0.6 on 2026-07-20 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_perfil_cnpj_alter_perfil_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='empresa',
            field=models.CharField(blank=True, max_length=200, verbose_name='Empresa'),
        ),
        migrations.CreateModel(
            name='RegraAtribuicaoPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('empresa', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regras_atribuicao', to='core.plano')),
            ],
            options={
                'verbose_name': 'Regra de Atribuição de Plano',
                'verbose_name_plural': 'Regras de Atribuição de Planos',
                'ordering': ['empresa'],
            },
        ),
    ]
