# Generated by Django 6.0.6 on 2026-07-21 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_avatar_to_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='lives/', verbose_name='Imagem')),
                ('url_externa', models.URLField(blank=True, help_text='Link do YouTube Live ou Vimeo Live.', verbose_name='URL externa')),
                ('data_hora', models.DateTimeField(verbose_name='Data e hora')),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('ao_vivo', 'Ao Vivo'), ('encerrada', 'Encerrada')], default='agendada', max_length=10)),
                ('is_gratuito', models.BooleanField(default=False, verbose_name='Gratuito')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ambiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lives', to='core.ambiente', verbose_name='Academy')),
            ],
            options={
                'verbose_name': 'Live',
                'verbose_name_plural': 'Lives',
                'ordering': ['-data_hora'],
                'permissions': [('gerenciar_lives', 'Pode gerenciar lives')],
            },
        ),
    ]
