# Generated by Django 6.0.6 on 2026-07-22 21:17

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0028_add_live'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembroOrcoma',
            fields=[
            ],
            options={
                'verbose_name': 'Membro Orcoma',
                'verbose_name_plural': 'Membros Orcoma',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
