# Generated by Django 6.0.6 on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_membro_orcoma_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='unidade',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', '---------'),
                    ('maracas', 'Maracás'),
                    ('salvador', 'Salvador'),
                    ('aguacara', 'Jaguaquara'),
                    ('jequie_1', 'Jiquié 1'),
                    ('jequie_2', 'Jequié 2'),
                    ('seabra', 'Seabra'),
                    ('itaberaba_publica', 'Itaberaba (Orcoma Pública)'),
                    ('itaberaba', 'Itaberaba'),
                    ('feira_de_santana', 'Feira de Santana'),
                    ('jiquirica', 'Jiquiriça'),
                    ('ruy_barbosa', 'Ruy Barbosa'),
                    ('sao_paulo', 'São Paulo'),
                    ('utinga', 'Utinga'),
                    ('varzea_nova', 'Várzea Nova'),
                ],
                max_length=30,
                verbose_name='Unidade',
            ),
        ),
    ]
