# Generated by Django 6.0.6 on 2026-07-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_perfil_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='is_empresario',
            field=models.BooleanField(default=False, verbose_name='É Empresário?'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='regime_federal',
            field=models.CharField(blank=True, choices=[('', '---------'), ('mei', 'MEI'), ('me', 'ME'), ('epp', 'EPP')], max_length=10, verbose_name='Regime Federal'),
        ),
    ]
