# Generated by Django 6.0.6 on 2026-07-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_perfil_regime_federal_is_empresario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cargo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cargo'),
        ),
    ]
