# Generated by Django 6.0.6 on 2026-07-27 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_perfil_cargo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Live',
        ),
    ]
