# Generated by Django 6.0.6 on 2026-07-27 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_delete_live'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssinaturaPlano',
        ),
    ]
