# Generated by Django 6.0.6 on 2026-07-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_delete_assinaturaplano'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='tempo_total_assistido',
            field=models.FloatField(default=0, help_text='Tempo total acumulado assistido em segundos'),
        ),
        migrations.AddField(
            model_name='metasemanal',
            name='baseline_tempo',
            field=models.FloatField(default=0, help_text='Tempo total acumulado (em segundos) no momento da criação da meta'),
        ),
    ]
