# Generated by Django 6.0.6 on 2026-07-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_matricula_tempo_total_assistido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='url',
            field=models.URLField(blank=True, verbose_name='Link externo'),
        ),
    ]
