# Generated by Django 6.0.6 on 2026-07-28 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_add_evento_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('tipo', models.CharField(choices=[('boas_vindas', 'Boas-vindas'), ('curso_concluido', 'Curso Concluído'), ('evento', 'Evento')], max_length=20)),
                ('lida', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, help_text='URL opcional para ação relacionada', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario', 'lida', '-created_at'], name='core_notifi_usuario_5f705c_idx')],
            },
        ),
    ]
