# Generated by Django 6.0.6 on 2026-08-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiente',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='ambientes/', verbose_name='Imagem de Capa'),
        ),
    ]
