# Generated by Django 6.0.6 on 2026-08-12 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_ambiente_imagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lida_em', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='core.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_leituras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leitura de Evento',
                'verbose_name_plural': 'Leituras de Eventos',
                'unique_together': {('usuario', 'evento')},
            },
        ),
    ]
