# Generated by Django 6.0.6 on 2026-08-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_eventoleitura'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='aulas_concluidas',
            field=models.JSONField(blank=True, default=list, help_text='Chaves das aulas concluídas neste curso (sincronizado entre dispositivos).'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='ultima_aula',
            field=models.JSONField(blank=True, default=dict, help_text='Última aula assistida (ex.: {"moduloIdx": 0, "aulaIdx": 2}).'),
        ),
    ]
