# Generated by Django 6.0.6 on 2026-08-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_matricula_aulas_concluidas_matricula_ultima_aula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('cliente_premium', 'Cliente Premium'), ('cliente_vex', 'Cliente Vex'), ('empresário', 'Empresário'), ('cliente_equipe', 'Cliente Time'), ('colaborador_vex', 'Colaborador Visão Tributária'), ('gestor_orcoma', 'Gestor Orcoma (interno)'), ('visitor', 'Visitante')], db_index=True, default='cliente_vex', max_length=30),
        ),
    ]
